### ISSUE TITLE
Require binaries for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [NVIDIA/DCGM#10]
Hi Team, 

I am working on building a **nvidia/dcgm-exporter** image for arm64 but found that it is installing **datacenter-gpu-manager** binaries which is not available for ARM64 in official releases. 

I have followed the step provided in this[ link](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-user-guide/getting-started.html) and tried to install binary for arm64, but it is not getting installed for arm64. However, I am able to install successfully in amd64 by following the same. 

Do you have any plans to release **datacenter-gpu-manager** binaries for linux-arm64? 

It will be very helpful if arm64 binaries are released. If required, I am happy to contribute

**Comment by nikkon-dev** [comment]
Hi,

We publish the arm64 version to the official Cuda repository:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/

The only arm64 architecture we support is SBSA. We do not support Tegra, for example.

WBR,
Nik
