### ISSUE TITLE
I stopped nvidia-dcgm.service and disabled auto-restart. I still see dcgmi CLI working. Will dcgmi CLI not use nvidia-dcgm.service?

### ISSUE THREAD

**Issue by vinayburugu** [NVIDIA/DCGM#108]
stopped nvidia-dcgm.service and disabled auto-restart. I still see dcgmi CLI working. Will dcgmi CLI not use nvidia-dcgm.service? If not, what does dcgmi CLI talk to to get the health status of the gpu?

**Comment by nikkon-dev** [comment]
@vinayburugu,

If the standalone nv-hostengine is not running, the dcgmi CLI tool can execute an embedded hostengine. However, in this scenario, the hostengine will only have privileges equivalent to the user running the dcgmi command. It's important to note that certain functionalities may not work as they require root privileges.

**Comment by vinayburugu** [comment]
@nikkon-dev,
Can I have a new nv-hsotengine in embedded mode and also run the default nv-hostengine on the same instance?

**Comment by nikkon-dev** [comment]
@vinayburugu,

Having multiple nv-hostengine instances on the same node is highly not recommended and not an officially supported configuration. The embedded hostengine will not communicate, inherit permissions, or synchronize its work with any other nv-hostengine instance, which may lead to deadlocks in the driver.

**Comment by vinayburugu** [comment]
@nikkon-dev,
Thank you for the explanation.

Will the embedded hostengine executed by dcgmi CLI be shutdown once a specific dcgmi command executed? i.e. will it use a new embedded hostengine everytime a dcgmi command is executed?

**Comment by nikkon-dev** [comment]
@vinayburugu,

Hostengine is loaded as a shared library into the dcgmi process. When the process terminates, the hostengine also stops.
