### ISSUE TITLE
question about : reference implementation of DCGM + NCCL multi-node testing.

### ISSUE THREAD

**Issue by dmonakhov** [NVIDIA/DCGM#109]
Hi, release nodes for 5.2.3 https://docs.nvidia.com/datacenter/dcgm/latest/release-notes/changelog.html#id3 has following note

```Added a reference implementation of DCGM + NCCL multi-node testing.```
But  I failed to find it, can you please point where it can be found

**Comment by nikkon-dev** [comment]
@dmonakhov,

The multi-node reference is added in https://github.com/NVIDIA/DCGM/pull/110

**Comment by dmonakhov** [comment]
Reopen this issue because code merged is broken.
