### ISSUE TITLE
Missing EUD Package Link on Guide

### ISSUE THREAD

**Issue by canerozer** [NVIDIA/DCGM#118]
Hello,
I was willing to run the extensive utility diagnostic tests but I wasn't able to download and install the repo package, `nvidia-diagnostic-local-repo-ubuntu2204-525.125.06-mode1_1.0-1_amd64.deb`. Can you add the link to that package on your DCGM guide for version 3.2?
Best,

**Comment by glowkey** [comment]
Unfortunately that package is not generally available at this time.

**Comment by disjustin** [comment]
@glowkey update on possible release or alternative? Looking for MLE decoding tool `mle` which only seems to be provided in EUD package.

**Comment by glowkey** [comment]
Unfortunately there are no updates.

**Comment by ethanlindemann** [comment]
@glowkey Just checking in if there are any plans, updates, or timelines for making this package GA? We would like to utilize these diagnostics in our testing.

**Comment by glowkey** [comment]
Nothing that I am aware of. I would recommend using enterprise (as opposed to community) support channels to prioritize this request.
