### ISSUE TITLE
How to use profiling from python bindings?

### ISSUE THREAD

**Issue by optyang** [NVIDIA/DCGM#123]
Hi, I would like to use profiling from the python bindings. It seems to me that the python class [`DcgmGroupProfiling`](https://github.com/NVIDIA/DCGM/blob/master/testing/python3/DcgmGroup.py#L519) is lacking a method `dcgmProfWatchFields` (and `dcgmProfUnwatchFields`), which is the C++ counterpart defined at [here](https://github.com/NVIDIA/DCGM/blob/a4e74cc3ab2be68bdae3bbb06c9a83fb5d4005a9/dcgmlib/dcgm_agent.h#L1918). 

Am I missing anything or is there a workaround? Thanks.

**Comment by nikkon-dev** [comment]
@optyang,

Which DCGM version are you using? The `dcgmProfWatchFields` and `dcgmProfUnwatchFields` are deprecated, and you should use the DCGM_FI_PROF* fields as any other field with dcgmWatchFields API.

**Comment by optyang** [comment]
> @optyang,
> 
> Which DCGM version are you using? The `dcgmProfWatchFields` and `dcgmProfUnwatchFields` are deprecated, and you should use the DCGM_FI_PROF* fields as any other field with dcgmWatchFields API.

Thanks a lot!
