### ISSUE TITLE
device memory ECC Errors can not take effect

### ISSUE THREAD

**Issue by xiaohai1234** [NVIDIA/DCGM#126]
Hello,
With the command "**_dcgmi test --inject --gpuid 0 -f 319 -v 4_**", I can inject Device memory double bit volatile ECC errors, and it will show successfully info.
But if I use the command "**_nvidia-smi -q -d ECC_**" to check error, the ECC count will not change.
Is there a way to inject real memory ECC faults ?
thanks.

**Comment by nikkon-dev** [comment]
@xiaohai1234,

The dcgmi injected errors are just added values in the internal dcgm cache and only affect dcgm tools and policies. There is no way to inject a real ECC error into the hardware.

**Comment by xiaohai1234** [comment]
@nikkon-dev ,
thanks.
