### ISSUE TITLE
Build dcgm container images

### ISSUE THREAD

**Issue by mgiessing** [NVIDIA/DCGM#17]
Hi, I'm currently a bit confused - is this the repository to build these container images?
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/cloud-native/containers/dcgm

I want to build ppc64le container images, because in ngc there are only x86 images, however it seems the corresponding tags are missing in this git (e.g. the latest 2.3.2). On the other side I can see that those packages are being built for Power if I search for `datacenter-gpu-manager` in the repository
https://developer.download.nvidia.com/compute/cuda/repos/rhel8/ppc64le/

I'd appreciate instructions on how to build the the images :) 

Thanks a lot!

**Comment by nikkon-dev** [comment]
@mgiessing,
I've just updated the repository to contain DCGM v2.3.4, which has docker files [here](https://github.com/NVIDIA/DCGM/tree/master/docker).

As you mentioned, we do not provide ppc64le images, but we provide Debian and rpm packages for that platform. 
You will have to manually change the source of the DCGM packages for the ppc64le platform in the Dockerfiles.
For example:
`https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64`
should be changed to 
`https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/ppc64el`
Notice that the latest Ubuntu version we support for ppc64le is 18.04, not 20.04

**Comment by mgiessing** [comment]
The docker files work like a charm - thanks a lot!
One small note, for ubuntu also the base image must be changed to `nvcr.io/nvidia/cuda:11.1.1-base-ubuntu18.04`, because 11.1.1 seems the latest image that supports ppc64le
