### ISSUE TITLE
How to get current memory usage in bytes from dmon?

### ISSUE THREAD

**Issue by johnsushant** [NVIDIA/DCGM#177]
Is there a way to get current GPU memory usage in bytes from dmon? I would ideally expect a field like `DCGM_FI_GPU_MEMORY_USAGE` which provides this metric.

Is there any other recommended way to do this other than calling the NVML API directly?

**Comment by glowkey** [comment]
You can try [DCGM_FI_DEV_FB_USED](https://docs.nvidia.com/datacenter/dcgm/2.4/dcgm-api/dcgm-api-field-ids.html#c.DCGM_FI_DEV_FB_USED), it is in MB though. DCGM_FI_GPU_MEMORY_USAGE is not a valid field.
