### ISSUE TITLE
failed to trigger dcgm service

### ISSUE THREAD

**Issue by devounoide** [NVIDIA/DCGM#19]
Dear to whom it may concern,

We observed this following error a lot with dcgm script.
[root@gpu06 ~]# less /opt/slurm/tmp/gpu-stats-871006-gpu06.cluster.out
Error: Unable to retrieve job statistics. Return: No data is available.
It worked for some jobs, while fails for other jobs. No clue as what is happening.

When I checked the service, it is running.
[root@gpu06 ~]# systemctl status dcgm.service
● dcgm.service - DCGM service
   Loaded: loaded (/etc/systemd/system/dcgm.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-01-07 17:03:34 CST; 1 weeks 5 days ago
 Main PID: 1712 (nv-hostengine)
    Tasks: 7 (limit: 2464686)
   Memory: 32.6M
   CGroup: /system.slice/dcgm.service
           └─1712 /usr/bin/nv-hostengine -n

Jan 07 17:03:34 gpu06.cluster systemd[1]: Started DCGM service.
Jan 07 17:03:39 gpu06.cluster nv-hostengine[1712]: DCGM initialized
Jan 07 17:03:39 gpu06.cluster nv-hostengine[1712]: Host Engine Listener Started

I wonder if something in my prologue or epilogue script is not set correctly.
Could you look at them? See files attached. Much appreciated!
[prologue.txt](https://github.com/NVIDIA/DCGM/files/8188973/prologue.txt)
[epilogue.txt](https://github.com/NVIDIA/DCGM/files/8188974/epilogue.txt)

**Comment by nikkon-dev** [comment]
@devounoide,
The Job statistics work only for processes that start after `dcgmi stats -g $groupid --enable`. If a process existed before the stats were enabled, no information would be available.

**Comment by devounoide** [comment]
@nikkon-dev 
Never mind, I have figured out the solution. Thanks!
