### ISSUE TITLE
About dcgmError_enum 94 - DCGM_FR_EUD_NON_ZERO_EXIT_CODE. Anyone can told me what is reason to this case?

### ISSUE THREAD

**Issue by Pig255** [NVIDIA/DCGM#190]
Details are as follows:

"warnings" : "GPU 4 EUD process exited with non-zero exit code. Please check the EUD logs in '/var/log/nvidia-dcgm/dcgm_eud.log', '/var/log/nvidia-dcgm/dcgm_eud_stdout.txt', and '/var/log/nvidia-dcgm/dcgm_eud_stderr.txt' Exit code: 139"

all GPUs report such error

**Comment by Pig255** [comment]
![Image](https://github.com/user-attachments/assets/64d4a307-7e54-443c-add1-7580ecb4c12d)

**Comment by Pig255** [comment]
/usr/share/nvidia/diagnostic/specializediag: line 12:  Segmentation fault (core dumped)

**Comment by nikkon-dev** [comment]
@Pig255,

The EUD component is currently not publicly available and is only accessible to a limited number of customers. If you have access to it, you should be able to report a bug at the NvOnline portal and provide all the aforementioned log files and details.

Please note that the DCGM team does not maintain the EUD component, so we are unable to provide significant assistance with its crashes.
