### ISSUE TITLE
Simulating Errors for Testing

### ISSUE THREAD

**Issue by jarulsamy** [NVIDIA/DCGM#203]
Hi,

I've just added NVIDIA DCGM to our compute cluster to monitor our GPU health. So far everything is working well, and I am able to query GPU health regularly from our management nodes.

However, I haven't been able to thoroughly test this as I haven't had a hardware failure yet. Is there an easy way to simulate a hardware error for DCGM? I want to test my scripts to see if the appropriate actions are taken on our Slurm cluster.

Sorry if this is off-topic or within the docs somewhere, my google-fu is failing me.

**Comment by maxweiss** [comment]
DCGM Error Injection is probably what you're looking for: https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/dcgm-error-injection.html

**Comment by jarulsamy** [comment]
This looks like exactly what I want. Not sure how I missed this, thank you!
