### ISSUE TITLE
Err: Failed to start DCGM Server: -7

### ISSUE THREAD

**Issue by yanglinpei** [NVIDIA/DCGM#21]
root@test-install-nvidia-driver-with-monitoring:/home/linpei.yang# systemctl --now enable nvidia-dcgm
root@test-install-nvidia-driver-with-monitoring:/home/linpei.yang# nv-hostengine

ubuntu2004

**Comment by yanglinpei** [comment]
root@test-install-nvidia-driver-with-monitoring:/home/linpei.yang# nvidia-smi
Thu Mar 10 14:48:18 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    10W /  70W |    105MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       961      G   /usr/lib/xorg/Xorg                 95MiB |
|    0   N/A  N/A      1010      G   /usr/bin/gnome-shell                8MiB |
+-----------------------------------------------------------------------------+
root@test-install-nvidia-driver-with-monitoring:/home/linpei.yang#

**Comment by swagshaw** [comment]
I tried to change the port from 5555 to 8888. And it worked.

**Comment by nikkon-dev** [comment]
Please notice that running two nv-hostengine instances on the same hardware is not a supported scenario, even if you run them on different ports.

The nvidia-dcgm service runs nv-hostengine instance on the default 5555 port. Running another instance on port 8888 may lead to unpredictable errors and deadlocks in hardware.
