### ISSUE TITLE
Avoid the building for architectures that are not locally used during the image building stage

### ISSUE THREAD

**Issue by jbaksta** [NVIDIA/DCGM#28]
Is it possible in the future to have an option to avoid building architectures in the build image that are not going to be used. I'm specifically talking about the cross compilers being built and such. For example, we don't have ARM or PowerPC64-LE where we'd use DCGM.

I've been working on getting DCGM built, but when I hit an issue such as #27 -- The build has to start all the way at the beginning and this is not a fast build process and therefore seemingly takes many hours to iterate on.

**Comment by nikkon-dev** [comment]
Starting from DCGM 3.2.5, the dcgmbuild container can be built for each platform independently.

```
cd dcgmbuild
./build.sh amd64           # produces dcgmbuild-x64_64
./build.sh aarch64         # produces dcgmbuild-aarch64
./build.sh powerpc64le     # produces dcgmbuild-powerpc64le
./build.sh                 # produces all three variants
```

The main build.sh script will use the corresponding image for each target architecture.
