### ISSUE TITLE
When I try to use the dcgmi to monitor under  A100 MIG config, I got this problem

### ISSUE THREAD

**Issue by xichie** [NVIDIA/DCGM#31]
![image](https://user-images.githubusercontent.com/30527824/167289006-d4750ead-9fb1-4adf-ae42-bd38c8608cf0.png)
![image](https://user-images.githubusercontent.com/30527824/167289071-1589bb64-2db9-4247-ad62-32386465b55f.png)

**Comment by xichie** [comment]
cmd: dcgmi diag -r 1
print: GPU 0's MIG configuration is incompatible with the diagnostic because it prevents access to the entire GPU.

**Comment by nikkon-dev** [comment]
@xichie,

dcgmi diag does not support all MIG configurations at this moment. The only supported MIG configuration is when GPU instance occupies the whole GPU and has just one Compute instance. In general - that is configuration similar to disabled MIG.

**Comment by xichie** [comment]
> @xichie,
> 
> dcgmi diag does not support all MIG configurations at this moment. The only supported MIG configuration is when GPU instance occupies the whole GPU and has just one Compute instance. In general - that is configuration similar to disabled MIG.

thank you！And I want to use dcgm with python to get some metrics under MIG configuration，such as sm utilization，gpu instance memory utilization etc. I am not ensure dcgm can do this. Could you give me a example？

**Comment by nikkon-dev** [comment]
Here is an example of how to get DCP metrics for the whole GPU: [test_prof.py](https://github.com/NVIDIA/DCGM/blob/master/testing/python3/tests/test_prof.py)

And here is an example of how to work with GPU/Compute instances: [test_instances.py](https://github.com/NVIDIA/DCGM/blob/master/testing/python3/tests/test_instances.py)

**Comment by xichie** [comment]
> cmd: dcgmi diag -r 1 print: GPU 0's MIG configuration is incompatible with the diagnostic because it prevents access to the entire GPU.

Thank you so much for your help! 🙏🙏🙏

**Comment by ytaoeer** [comment]
hi, i want to do the same thing, Using python to get mig device's metrics. But i dont understand this code [test_instances.py](https://github.com/NVIDIA/DCGM/blob/master/testing/python3/tests/test_instances.py). how can i use this code to get mig's metrics, for example, sm utilization

**Comment by ytaoeer** [comment]
My understanding is that dcgm python interface cannot handle mig directly, so extra fake instances are created. My problem is how can i use the fake instance to get mig's metrics
