### ISSUE TITLE
Error: Unable to Get supported metric groups

### ISSUE THREAD

**Issue by xichie** [NVIDIA/DCGM#32]
![image](https://user-images.githubusercontent.com/30527824/167368224-3bd47263-cd19-4fb0-9cdb-c042d462c721.png)
I run this command with MIG on A100,  and got this ERROR.

**Comment by xichie** [comment]
![image](https://user-images.githubusercontent.com/30527824/167368877-4a983173-0901-4447-b03b-c5be7497c7f5.png)

**Comment by nikkon-dev** [comment]
@xichie,

Which version have you used before?
`dcgmi -v` should show both dcgmi (client) and nv-hostengine (server) versions.

For MIG-enabled systems, you may use `dcgmi discovery -c` to get information about the MIG topology.
