### ISSUE TITLE
Error: Cannot find the DCGM Python bindings

### ISSUE THREAD

**Issue by swagshaw** [NVIDIA/DCGM#37]
![image](https://user-images.githubusercontent.com/48468760/168956905-7e26b1e8-b022-47fb-9dd1-d9b060eb34d5.png)
The document told us that we should find the python bindings from `/usr/src/dcgm/bindings`. But the python bindings are exactly in the `/usr/local/dcgm/bindings`. Please update the document.

**Comment by nikkon-dev** [comment]
@swagshaw,

Thank you for the report. We will fix the path in the further doc updates.
