### ISSUE TITLE
I can not use nvvs to View fp16 tensor core peak flops vs theoretical flops

### ISSUE THREAD

**Issue by zcuuu** [NVIDIA/DCGM#40]
hi as we know A100 FP16 tensor core flos ls 312Tflops,but i want to sure could i get the theoretical value,when i use cublas or cutlass ,from the kernel ,i can get about 80% of the theoretical value.
so i want to know how to use the nvvs to View fp16 tensor core peak flops vs theoretical flops

thank u

**Comment by nikkon-dev** [comment]
@zcuuu,

It's doubtful you would be able to see the 100% TC utilization without using specially crafted synthetic kernels that do nothing but TC computation. Using cublas/cutlass, you could reach 90-95% utilization, but the library overhead will eat the rest. 
You could use `dcgmproftester11 -t 1004` to see about 90-95% utilization. This is the testing tool we use to generate GPU load to verify metrics. 

WBR,
Nik
