### ISSUE TITLE
Different explanations for field id 211

### ISSUE THREAD

**Issue by mintchocohoco** [NVIDIA/DCGM#45]
What exactly does feature filed id 211 mean?

- As a result of dcgmi dmon -l , feature 211 is written as gpu_util_samples (GUSAM). 
- By the way https://docs.nvidia.com/datacenter/dcgm/1.7/dcgm-api/group__dcgmFieldIdentifiers.html nothing written in this link.
- Also, https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/bindings/go/dcgm/dcgm_fields.h says SM utilization samples. 

What is the correct explanation and what exactly does it mean?

**Comment by nikkon-dev** [comment]
@mintchocohoco,

Public API clients cannot use the following fields.
DCGM_FI_DEV_SUPPORTED_TYPE_INFO
DCGM_FI_DEV_GRAPHICS_PIDS
DCGM_FI_DEV_COMPUTE_PIDS
DCGM_FI_DEV_GPU_UTIL_SAMPLES
DCGM_FI_DEV_MEM_COPY_UTIL_SAMPLES
Those fields are used inside the hostengine to compute Job-related statistics, but there is no public API to handle the samples on the client side.
In general, the value you get when you fetch DCGM_FI_DEV_GPU_UTIL_SAMPLES via public API is just one sample for some process out of ~100. Hostengine can read all samples and aggregate utilization for each process based on them, but you will not be able to do the same via libdcgm.so client API.

We will remove (move to internal headers) those fields from the public API in the subsequent releases.

WBR,
Nik
