### ISSUE TITLE
build error from ct-ng build

### ISSUE THREAD

**Issue by liuyibox** [NVIDIA/DCGM#6]
I just follow the github guide `sudo ./build.sh` to build this dcgm, however I keep getting the error when it comes to the `ct-ng build` command in the Dockerfile.

<img width="1035" alt="Screen Shot 2021-08-19 at 1 30 23 AM" src="https://user-images.githubusercontent.com/24197492/130019317-fe497489-9e41-4fe2-ac68-86a80bfbda79.png">

I then try to ignore the Dockfile and build on my own in my local machine. In this way, when I use the `CT_PREFIX=/opt/cross ct-ng build  -j12` on my command line, it gives the same error. I checked out the build.log file, it says ct-ng tries to create a director named '', which is not possible although I don't know why ct-ng wants to do that there. Here is the build.log error message. Is this where the cause of the error is?

<img width="1439" alt="Screen Shot 2021-08-19 at 1 35 21 AM" src="https://user-images.githubusercontent.com/24197492/130019730-262fbeab-300f-42f8-82a4-a5ab8112acf5.png">

I tried finding solutions, but I have not got one. Please let me know if you can repeat this error and has the solution.

**Comment by nikkon-dev** [comment]
@liuyibox,
Answered in the crosstool-ng thread https://github.com/crosstool-ng/crosstool-ng/issues/1580#issuecomment-902998892

We will update this build image at the next publication of the DCGM.
Sorry for the inconvenience.
