### ISSUE TITLE
 Error adding GPU 1 to group: This GPU is not supported by DCGM 

### ISSUE THREAD

**Issue by hugoren** [NVIDIA/DCGM#61]
dcgmi version: 3.1.3
dcgm-exporter version: 3.1.3-3.1.2
NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2  
the gpu is v100
my question:
    dcgm-exporter 
    INFO[0000] Starting dcgm-exporter                       
   INFO[0000] DCGM successfully initialized!               
   INFO[0000] Collecting DCP Metrics                       
   INFO[0000] No configmap data specified, falling back to metric file /etc/dcgm-exporter/default-counters.csv 
   INFO[0000] Initializing system entities of type: GPU    
   FATA[0000] Error adding GPU 1 to group: This GPU is not supported by DCGM

**Comment by nikkon-dev** [comment]
Hi @hugoren,

Looking at the provided logs, there are not one but at least two GPUs installed in the system. 
If you can run `nvidia-smi -q` on the node and provide the output, I could tell better why GPU 1 is not supported.
Another option would be to explicitly set the GPU indices in the dcgm-exporter configuration by changing the arguments for the dcgm-exporter command line (usually in Values.yaml if you deploy via Helm).

**Comment by hugoren** [comment]
Hi,  thanks.
[root@localhost ~]# nvidia-smi -q

==============NVSMI LOG==============

Timestamp                                 : Tue Jan  3 14:04:32 2023
Driver Version                            : 460.106.00
CUDA Version                              : 11.2

Attached GPUs                             : 2
GPU 00000000:17:00.0
    Product Name                          : Tesla V100S-PCIE-32GB

**Comment by hugoren** [comment]
I deploy via 'dcgm-exporter /etc/dcgm-exporter/default-counters.csv'

**Comment by nikkon-dev** [comment]
The nvidia-smi output does not look complete, but it, indeed says "Attached GPUs: 2". 

The `dcgm-exporter -d g:0` argument should tell DCGM to monitor GPU_0 only.

**Comment by hugoren** [comment]
Yes, there are two GPUs.
one is GeForce GT 710  , another is Tesla V100S

**Comment by nikkon-dev** [comment]
GT 710 is not supported for DCGM monitoring. You need to exclude that GPU from the dcgm-exporter config

**Comment by hugoren** [comment]
root@localhost ~]# dcgm-exporter -d g:0
INFO[0000] Starting dcgm-exporter                       
INFO[0000] DCGM successfully initialized!               
INFO[0000] Collecting DCP Metrics                       
INFO[0000] No configmap data specified, falling back to metric file /etc/dcgm-exporter/default-counters.csv 
INFO[0000] Initializing system entities of type: GPU    
FATA[0000] Error adding GPU 1 to group: This GPU is not supported by DCGM

**Comment by hugoren** [comment]
-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100S-PCI...  Off  | 00000000:17:00.0 Off |                    0 |
| N/A   40C    P0    37W / 250W |      0MiB / 32510MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GT 710      Off  | 00000000:18:00.0 N/A |                  N/A |
| 40%   38C    P0    N/A /  N/A |      0MiB /  2001MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+---------

**Comment by hugoren** [comment]
The 0 is Tesla V100S.

**Comment by hugoren** [comment]
I change the version of dcgmi from 3.1.3 to 2.1.4 .
Then dcgm-exporter -d g:0
It run successed.
Thank you at all.

**Comment by hugoren** [comment]
@nikkon-dev  
Thank you very much.
