### ISSUE TITLE
Question about job statistics

### ISSUE THREAD

**Issue by starry91** [NVIDIA/DCGM#73]
Are DCGM [Job statistics](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#job-statistics) supported for GPU Instance (MIGs) as well? Doc only mentions GPUs.

I am looking to track the statistics of a job (this would have a start and end) which would use multiple GPU Instances (MIGs). So, wanted to know this can be achieved via DCGM job statistics feature.

**Comment by nikkon-dev** [comment]
@starry91,

The Job statistic utilizes [Accounting mode](https://docs.nvidia.com/deploy/nvml-api/group__nvmlAccountingStats.html) under the hood. Unfortunately, Accounting mode does not support MIG-enabled configurations.
