### ISSUE TITLE
How to monitor specific GPU

### ISSUE THREAD

**Issue by LukeLIN-web** [NVIDIA/DCGM#87]
I only know this command which can work:
```
dcgmi dmon -e 1002,1003,1005,1009,1010 -c 10 -d 10000 
```
But it shows all GPU statuses. How to measure specific GPU status?

By the way, I wonder what is the unit of `PCIe Bandwidth` ? 864034668 means 864MB/s PCIe bandwidth?

**Comment by nikkon-dev** [comment]
@LukeLIN-web,

To specify which GPUs/MIG instances to use, you can utilize the `-i` argument in the dcgmi commands.

The PCIe bandwidth is measured in bytes per second, so 864MB/s is correct.

**Comment by LukeLIN-web** [comment]
> @LukeLIN-web,
> 
> To specify which GPUs/MIG instances to use, you can utilize the `-i` argument in the dcgmi commands.
> 
> The PCIe bandwidth is measured in bytes per second, so 864MB/s is correct.

Thank you for your reply!
