### ISSUE TITLE
PROF_PCIE_[T|R]X_BYTES is N/A in A100 mig 

### ISSUE THREAD

**Issue by luckqk** [NVIDIA/DCGM#88]
Is PROF_PCIE_[T|R]X_BYTES supported in A100 mig mode?
I ran this cmd `dcgmi dmon -e 1009,1010 -g 16`  and give me a return below
![image](https://github.com/NVIDIA/DCGM/assets/42504958/d4d0cdf4-8da6-43bc-bcd7-c824ef2c3dcc)

I can fetch PROF_GR_ENGINE_ACTIVE,PROF_SM_ACTIVE or other.  
How to debug or can you give me some advice?

Condition:
GPU: A100
dcgm-exporter version: 3.1.8-3.1.5
nv-hostengine: 3.1.8

**Comment by nikkon-dev** [comment]
@luckqk,

The PCI_TX/RX metric does not have any physical meaning for MIG. Thus we return N/A for MIG instances/compute instances. Only the whole GPU will get the values.

**Comment by luckqk** [comment]
> @luckqk,
> 
> The PCI_TX/RX metric does not have any physical meaning for MIG. Thus we return N/A for MIG instances/compute instances. Only the whole GPU will get the values.

Thanks for your reply.
