### ISSUE TITLE
How is NVIDIA DCGM Documentation built from sources?

### ISSUE THREAD

**Issue by hwhsu1231** [NVIDIA/DCGM#92]
### Question

I found an official [NVIDIA DCGM Documentation](https://docs.nvidia.com/datacenter/dcgm/latest/), which is built with [Sphinx](https://github.com/sphinx-doc/sphinx).

However, I couldn't find Sphinx's [configuration file](https://www.sphinx-doc.org/en/master/usage/configuration.html), `conf.py` in this repository.

Therefore, I wonder how NVIDIA DCGM Documentation is built from sources?

### Screenshots

![image](https://github.com/NVIDIA/DCGM/assets/71438617/58b2657d-6150-42fc-b9ab-ea4bf7806c11)
![image](https://github.com/NVIDIA/DCGM/assets/71438617/78a7b312-c4e4-4514-af6a-c7ec18568d97)

**Comment by nikkon-dev** [comment]
Hi @hwhsu1231,

You're right that Sphinx was used to build the official documentation, but unfortunately, it's not open-sourced and it's not part of this repository.

We don't have any plans to open-source it right now.

Best regards,
Nik
